trigger:
- master
- dev

pr:
- master

stages:


- stage: copy-files
  displayName: Copy Python Files
  jobs:
  - template: steps/copy-files.yml

############################### Tactical Mgmt ############################### 
- stage: 
  displayName: Tactical Mgmt
  dependsOn: copy-files
  condition: succeeded('copy-filesk')
  jobs:
  - template: steps/f5-backup.yml
    parameters:
      keyvaultname: $(KEY_VAULT_NAME)
      azureclientid: $(AZURE_CLIENT_ID)
      azureclientsecret: $(NONPROD_CLIENT_SECRET)
      storagestring: $(NONPROD_STORAGE_CONNECTION_STRING)
      storagename: $(NONPROD_STORAGE_CONTAINER_NAME)
      f5username:
      f5password:

############################### Hub Non-Prod ############################### 
- stage: 
  displayName: Hub Non-Prod
  dependsOn: copy-files
  condition: succeeded('copy-filesk')
  jobs:
  - template: steps/f5-backup.yml
    parameters:
      keyvaultname: $(KEY_VAULT_NONPROD)
      azureclientid: $(NONPROD_CLIENT_ID)
      azureclientsecret: $(NONPROD_CLIENT_SECRET)
      storagestring: $(NONPROD_STORAGE_CONNECTION_STRING)
      storagename: $(NONPROD_STORAGE_CONTAINER_NAME)
      f5username:
      f5password:

############################### Hub Prod ############################### 
- stage: 
  displayName: Hub Prod
  dependsOn: copy-files
  condition: succeeded('copy-filesk')
  jobs:
  - template: steps/f5-backup.yml
    parameters:
      keyvaultname: $(KEY_VAULT_PROD)
      azureclientid: $(PROD_CLIENT_ID)
      azureclientsecret: $(PROD_CLIENT_SECRET)
      storagestring: $(PROD_STORAGE_CONNECTION_STRING)
      storagename: $(PROD_STORAGE_CONTAINER_NAME)
      f5username:
      f5password:
