trigger:
- master
- dev

pr:
- master

pool:
    name: rdo-backup-prod
    vmImage: Ubuntu-18.04

steps:

  - task: CopyFiles@1
    displayName: Copy Python files
    inputs:
      contents: '**'
      TargetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: f5_backup.py
    workingDirectory: $(Build.ArtifactStagingDirectory)