trigger:
- master
- dev

pr:
- master

pool:
    name: rdo-backup-prod
    vmImage: Ubuntu-18.04

strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:

- task: CopyFiles@1
  displayName: Copy Python files
  inputs:
    contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true

- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- task: PythonScript@0
  displayName: Execute Python script
  inputs:
    scriptSource: 'filePath'
    scriptPath: f5_backup.py
    workingDirectory: $(Build.ArtifactStagingDirectory)