trigger:
- master
- dev

pr:
- master

# variables:
#   AZURE_KEY_VAULT: '$(key_vault)'

pool:
    name: rdo-backup-prod
    vmImage: Ubuntu-18.04

steps:
- task: CopyFiles@1
  displayName: Copy Python files
  inputs:
    contents: '**'
    TargetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true

- task: PythonScript@0
  displayName: Execute Python script
  env: 
    KEY_VAULT_NAME: $(KEY_VAULT_NAME)
  inputs:
    scriptSource: 'filePath'
    scriptPath: f5_backup.py
    arguments: --KEY_VAULT_NAME $(KEY_VAULT_NAME)
    workingDirectory: $(Build.ArtifactStagingDirectory)