trigger:
- master
- dev

pr:
- master

stages:


- stage: copy-files
  displayName: Copy Python Files
  jobs:
  - template: steps/copy-files.yml

############################### Tactical Mgmt ############################### 
- stage: 
  displayName: Tactical Mgmt
  dependsOn: copy-files
  condition: succeeded('copy-filesk')
  jobs:
  - template: steps/f5-backup.yml
    parameters:
      keyvaultname: $(KEY_VAULT_NAME)
      azureclientid: $(AZURE_CLIENT_ID)
      azureclientsecret: $(AZURE_CLIENT_SECRET)
      storagestring: $(AZURE_STORAGE_CONNECTION_STRING)
      storagename: $(AZURE_STORAGE_CONTAINER_NAME)
      f5username: $(TACTICAL_F5_USERNAME)
      f5password: $(TACTICAL_F5_PASSWORD)
      f5devices: $(TACTICAL_F5_DEVICES)

############################### Hub Non-Prod ############################### 
- stage: 
  displayName: Hub Non-Prod
  dependsOn: copy-files
  condition: succeeded('copy-filesk')
  jobs:
  - template: steps/f5-backup.yml
    parameters:
      keyvaultname: $(KEY_VAULT_NONPROD)
      azureclientid: $(NONPROD_CLIENT_ID)
      azureclientsecret: $(NONPROD_CLIENT_SECRET)
      storagestring: $(AZURE_STORAGE_CONNECTION_STRING)
      storagename: $(AZURE_STORAGE_CONTAINER_NAME)
      f5username: $(NONPROD_F5_USERNAME)
      f5password: $(NONPROD_F5_PASSWORD)
      f5devices: $(NONPROD_F5_DEVICES)

############################### Hub Prod ############################### 
- stage: 
  displayName: Hub Prod
  dependsOn: copy-files
  condition: succeeded('copy-filesk')
  jobs:
  - template: steps/f5-backup.yml
    parameters:
      keyvaultname: $(KEY_VAULT_PROD)
      azureclientid: $(PROD_CLIENT_ID)
      azureclientsecret: $(PROD_CLIENT_SECRET)
      storagestring: $(AZURE_STORAGE_CONNECTION_STRING)
      storagename: $(AZURE_STORAGE_CONTAINER_NAME)
      f5username: $(PROD_F5_USERNAME)
      f5password: $(PROD_F5_PASSWORD)
      f5devices: $(PROD_F5_DEVICES)
