jobs:
- job:
  pool:
      name: hmcts-cftptl-agent-pool
      vmImage: Ubuntu-18.04

  steps:

  - task: CopyFiles@1
    displayName: Copy Python files
    inputs:
      contents: '**'
      TargetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true
