jobs:
- job:
  pool:
      name: hmcts-cftptl-agent-pool
      vmImage: Ubuntu-18.04

  steps:

  - task: PythonScript@0
    displayName: Execute Python script
    inputs:
      scriptSource: 'filePath'
      scriptPath: f5_backup.py
      arguments: --KEY_VAULT_NAME ${{ parameters.keyvaultname }} --AZURE_TENANT_ID $(AZURE_TENANT_ID) --AZURE_CLIENT_ID ${{ parameters.azureclientid }} --AZURE_CLIENT_SECRET ${{ parameters.azureclientsecret }} --AZURE_STORAGE_CONNECTION_STRING ${{ parameters.storagestring }} --AZURE_STORAGE_CONTAINER_NAME ${{ parameters.storagename }} --F5_USERNAME ${{ parameters.f5username }} --F5_PASSWORD ${{ parameters.f5password }} --DEVICES ${{ parameters.f5devices }}  --F5_PORT ${{ parameters.f5port }}
      workingDirectory: $(Build.ArtifactStagingDirectory)
