jobs:
  - job:
    pool:
      name: hmcts-cftptl-agent-pool
      vmImage: Ubuntu-18.04

    steps:
      - task: AzureCLI@2
        displayName: Populate Netbox with Azure Prefixes
        inputs:
          azureSubscription: Reform-CFT-Prod
          workingDirectory: $(Build.ArtifactStagingDirectory)/drop/
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            #!/bin/bash
            set -e
            python3 -m venv rdo-backup
            . ./rdo-backup/bin/activate
            python3 -m pip install -U pip
            pip install --upgrade -r $(Build.ArtifactStagingDirectory)/drop/requirements.txt
            python3 $(Build.ArtifactStagingDirectory)/drop/netbox.py --KEY_VAULT_NAME ${{ parameters.keyvaultname }} --AZURE_TENANT_ID $(AZURE_TENANT_ID) --AZURE_CLIENT_ID ${{ parameters.azureclientid }} --AZURE_CLIENT_SECRET ${{ parameters.azureclientsecret }} --AZURE_STORAGE_CONNECTION_STRING ${{ parameters.storagestring }} --AZURE_STORAGE_CONTAINER_NAME ${{ parameters.storagename }} --F5_USERNAME ${{ parameters.f5username }} --F5_PASSWORD ${{ parameters.f5password }} --DEVICES ${{ parameters.f5devices }}  --F5_PORT ${{ parameters.f5port }}
